version: '3.8'

services:
  # --- SISTEMA DE MENSAJERÍA ---
  nats-server:
    image: nats:2.10-alpine
    container_name: tito-nats
    restart: unless-stopped
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222" # Cliente NATS (localhost)
      - "8222:8222" # Monitoring HTTP
    networks:
      - tito-network

  # --- BASE DE DATOS: USUARIOS ---
  postgres-usuarios:
    image: postgres:15-alpine
    container_name: tito-db-usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin # Usa claves simples para desarrollo local
      POSTGRES_DB: db_users
    ports:
      - "5433:5432" # Puerto mapeado al host
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data
    networks:
      - tito-network

  # --- BASE DE DATOS: PRODUCTOS ---
  postgres-productos:
    image: postgres:15-alpine
    container_name: tito-db-productos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_products
    ports:
      - "5434:5432" # IMPORTANTE: Puerto 5434 en localhost para evitar colisión con el 5432
    volumes:
      - pgdata_productos:/var/lib/postgresql/data
    networks:
      - tito-network

# (Añade aquí el resto de bases de datos para ms-orders, etc., cambiando los puertos externos ej: 5435, 5436)

volumes:
  pgdata_usuarios:
  pgdata_productos:

networks:
  tito-network:
    driver: bridge