services:
  postgres:
    image: postgres:15-alpine
    container_name: backend-mc-pnpm
    env_file:
      - .env
    environment:
      CONTEXT: /Jose/devops/DespAW/docker/Titos/proyectos/backend-mc-pnpm
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend-mc-pnpm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # Base de datos para Users
  # Cada servicio tiene su propia base de datos para mantener la separación de datos y facilitar la gestión.
  db-users:
    image: postgres:15
    container_name: postgres-users
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_users
    ports:
      - "5432:5432"
    volumes:
      - ./data/users:/var/lib/postgresql/data

  # Base de datos para Auth
  db-auth:
    image: postgres:15
    container_name: postgres-auth
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_auth
    ports:
      - "5433:5432"
    volumes:
      - ./data/auth:/var/lib/postgresql/data

  # Base de datos para Products
  # Prueba para que funcione el jeninsfile
  db-products:
    image: postgres:15
    container_name: postgres-products
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_products
    ports:
      - "5434:5432"
    volumes:
      - ./data/products:/var/lib/postgresql/data

  # Base de datos para Orders
  db-orders:
    image: postgres:15
    container_name: postgres-orders
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_orders
    ports:
      - "5435:5432"
    volumes:
      - ./data/orders:/var/lib/postgresql/data

  # Base de datos para Tables
  db-tables:
    image: postgres:15
    container_name: postgres-tables
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_tables
    ports:
      - "5436:5432"
    volumes:
      - ./data/tables:/var/lib/postgresql/data

  # Base de datos para QR Codes
  db-qrcodes:
    image: postgres:15
    container_name: postgres-qrcodes
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_qrcodes
    ports:
      - "5437:5432"
    volumes:
      - ./data/qrcodes:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend-mc-pnpm-network:
    driver: bridge